#############################################
# 01) Variablen definieren
#############################################

# Logo
BANNER=$(cat <<'EOF'
    ____             _      _   _    _    ____
   |  _ \  __ _ _ __| | __ | \ | |  / \  / ___|
   | | | |/ _´ | ´__| |/ / |  \| | / _ \ \___ \
   | |_| | |_| | |  |   |  | |\  |/ ___ \ ___| |
   |____/ \__._|_|  |_|\_\ |_| \_/_/   \_\____/
Data belongs in the dark. Simple. Silent. Reliable.
EOF
)

# Hostname fuer DarkNAS
HOSTNAME_DARKNAS="darkNAS"

# Admin-Benutzer fuer DarkNAS
ADMINUSER="darkroot"

# Initialpasswort für Admin-Benutzer (unbedingt ändern!!)
ADMINPASS="darkpass"

# System-User fuer ttyd (ohne Login, ohne Home)
TTYDUSER="ttyduser"

# Port fuer ttyd
TTYD_PORT="7681"

# DarkNAS Konfigurationspfade
CONFDIR="/etc/darknas"
CONFFILE="$CONFDIR/00_postinstall.conf"

# Logging
LOGDIR="/var/log/darknas"
DATE=$(date +"%Y-%m-%d")

# sudoers-Datei
SUDOERS_FILE="/etc/sudoers.d/darknas"

# Podmanuser
PODMANUSER="podmanuser"           # Name des dedizierten Podman-Users
PODMAN_CONF="/etc/darknas/podman.conf"
PODMAN_STACKDIR="/home/$PODMANUSER"

# Farbdefinitionen
NC="\033[0m"
CYAN="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"

msg()      { echo -e "${CYAN}[DarkNAS]${NC} $1" >/dev/tty; }
msg_ok()   { echo -e "${GREEN}[DarkNAS]${NC} $1" >/dev/tty; }
msg_warn() { echo -e "${YELLOW}[DarkNAS]${NC} $1" >/dev/tty; }
msg_err()  { echo -e "${RED}[DarkNAS]${NC} $1" >/dev/tty; }
